config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  get 'rakuten/query'
  get 'goods/query'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#authorize'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  constraints(id: /[0-9]+/) do
    resources :goods do
      collection do
        post :search
      end
    end
  end

  resources :customers, constraints: { id: /[0-9]+/ }

  constraints(id: /[0-9]+/) do
    resources :orders do
      collection do
        post :search
      end
    end
  end

  constraints(id: /[0-9]+/) do
    resources :order_details do
      collection do
        post  :search
      end
    end
  end

  constraints(id: /[0-9]+/) do
    resources :payments do
      collection do
        post  :search
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#hello'
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, length: {maximum: 255}, presence: true
  validates :snsid, length: {maximum: 255}
  validates :note, length: {maximum: 255}

  has_many :orders
  has_many :payments

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.where(attach_owner_user_id)
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(attach_owner_user_id(customer_params))

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = check_owner_user_id(Customer.find(params[:id]))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      @params = params.require(:customer).permit(:name, :snsid, :note)
      @params = attach_owner_user_id(@params)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
  def list_customers_for_combobox
    Customer.where({
      :owner_user_id => @current_user.id
      })
  end
end

app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => "form-horizontal customer" } do |f| %>

  <% if @customer.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :snsid, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :snsid, :class => 'form-control' %>
    </div>
    <%=f.error_span(:snsid) %>
  </div>
  <div class="form-group">
    <%= f.label :note, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :note, :class => 'form-control' %>
    </div>
    <%=f.error_span(:note) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customers_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>
<div class="col-xs-12" style="padding:5px;">
  <%= link_to t('.new', :default => t("helpers.links.new")), new_customer_path, :class => 'btn btn-primary' %>
</div>

  <% @customers.each do |customer| %>
    <div class="col-xs-12 list-group-item" style="padding:5px;">
      <span class="badge"><%= customer.created_at.strftime("%Y/%m/%d") %></span>
      <div class="col-xs-8">
        <span class="label label-info"><%= t '.name' %>:</span>
        <h3 class="list-group-item-heading"><%= link_to customer.name, customer_path(customer) %></h3>

        <p class="list-group-item-heading bg-warning"><span class="label label-warning"><%= t '.note' %>:</span><%= customer.note %></p>

        <p class="list-group-item-heading bg-warning"><span class="label label-default"><%= t '.snsid' %>:</span><%= customer.snsid %></p>
      </div>

      <div class="col-xs-12" style="padding:5px;">
        <%= link_to t('.show', :default => t("helpers.links.show")), customer_path(customer), :class => 'btn btn-info btn-xs pull-right' %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_customer_path(customer), :class => 'btn btn-info btn-xs pull-right' %>
      </div>

    </div>
    <!-- </li> -->
  <% end %>
</div>

app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.titleize %></h2>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @customer.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:snsid) %>:</strong></dt>
  <dd><%= @customer.snsid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:note) %>:</strong></dt>
  <dd><%= @customer.note %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(@customer), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<h2>All Orders</h2>

<%= render :partial => 'orders/list', locals: {orders: @customer.orders}%>