config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  get 'rakuten/query'
  get 'goods/query'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#authorize'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  constraints(id: /[0-9]+/) do
    resources :goods do
      collection do
        post :search
      end
    end
  end

  resources :customers, constraints: { id: /[0-9]+/ }

  constraints(id: /[0-9]+/) do
    resources :orders do
      collection do
        post :search
      end
    end
  end

  constraints(id: /[0-9]+/) do
    resources :order_details do
      collection do
        post  :search
      end
    end
  end

  constraints(id: /[0-9]+/) do
    resources :payments do
      collection do
        post  :search
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#hello'
end

app/models/order.rb
class Order < ApplicationRecord
  validate  :validate_customer_id

  belongs_to :customer
  has_many :orderDetails
  has_many :payments

  enum status: { new_order: 0, processing: 1, packaged: 3,  part_dispatch: 4,
                all_dispatch: 5, finished: 6, cancelled:99 }

  def self.search(params = {})
    Order.joins(:customer)
    .joins("left join (select sum(order_details.total_amount) as sum_total_amount, order_details.order_id from
              order_details group by order_details.order_id) order_details on orders.id = order_details.order_id")
    .joins("left join (select sum(payments.amounts) as sum_amounts, payments.order_id from
              payments group by payments.order_id) payments on payments.order_id = orders.id")
    .select("orders.*, customers.name as customer_name, order_details.sum_total_amount, payments.sum_amounts")
    .where(create_conditions(params)).order({id: :desc})
  end

  # raise system exception
  def validate_customer_id
    Customer.find(customer_id) rescue errors.addraise SystemError
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include OrdersHelper
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :order_search_params, only: [:search]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.search(attach_owner_user_id)
  end

  # POST /orders/search
  def search
    @orders = Order.search(@params)
    render "index"
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @customers = Customer.where(attach_owner_user_id)
    unless @customers.nil?
      @order.note = default_order_note_suffix_helper(@customers[0])
    end
  end

  # GET /orders/1/edit
  def edit
    @customers = Customer.where(attach_owner_user_id)
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(attach_owner_user_id(order_params))
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = check_owner_user_id(Order.find(params[:id]))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_id, :note, :status)
    end

    def order_search_params
      @params = params.require(:search).permit(:customer_id, :status)
      @params = attach_owner_user_id(@params)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def default_order_note_suffix_helper(customer = nil)
    (customer.nil? ? "" : customer.name) + I18n.t('orders.index.customer_order_suffix') + Time.now.strftime('%Y%m%d')
  end

  def list_order_details(order)
    order.orderDetails.search({
      :owner_user_id => @current_user.id
      })
  end

  def list_orders_for_combobox
    Order.where({
      :owner_user_id => @current_user.id
      }).order(id: :desc)
  end
end

app/views/orders/_form.html.erb
<%= form_for @order, :html => { :class => "form-horizontal order" } do |f| %>

  <% if @order.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :customer_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select :customer_id, @customers, :id, :name, {:selected => :customer_id}, {:class => 'form-control', :disabled => @order.persisted?}%>
    </div>
    <%=f.error_span(:customer_id) %>
  </div>
  <div class="form-group">
    <%= f.label :note, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :note, :class => 'form-control' %>
    </div>
    <%=f.error_span(:note) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :status, Order.statuses.keys.to_a.map { |s| [t("activerecord.enums.order.status.#{s}"), s]} , {}, {:class => 'form-control'} %>
    </div>
    <%=f.error_span(:status) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                orders_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>
<%= javascript_include_tag "orders/orders" %>
<%= javascript_tag do%>
var customer_order_text = '<%= default_order_note_suffix_helper %>';
<% end %>

app/views/orders/_list.html.erb
<% orders.each do |order| %>
    <div class="col-xs-12 list-group-item" style="padding:5px;">
      <span class="badge"><%= order.created_at.strftime("%Y/%m/%d") %></span>
      <div class="col-xs-12">
        <%= link_to  order_path(order) do %>
        <p>
          <span class="label label-info"><%= t "orders.index.order"%>: <%= order.note %></span>
        </p>
        <% end %>
        <p>
          <span class="list-group-item-heading bg-warning"><%= t "orders.index.status"%>:</span>
          <span class="label label-default"><%= t("activerecord.enums.order.status.#{order.status}") %></span>
        </p>
        <p>
          <span class="label label-danger"><%= t "orders.index.total_amount"%>: <%= number_to_currency(order.attributes["sum_total_amount"] || 0, :unit=>"CNY")%></span>
          <span class="label label-danger"><%= t "orders.index.payment"%>:<%= number_to_currency(order.attributes["sum_amounts"] || 0, :unit=>"CNY")
            %></span>
        </p>
      </div>

      <%if !order.attributes["customer_name"].nil? %>
      <div class="col-xs-12">
        <span class="list-group-item-heading">
          <%= t "orders.index.customer"%>: <%= link_to order.attributes["customer_name"], customer_path(order.customer_id) %>
        </span>
      </div>
      <% end %>
      <div class="col-xs-12">
        <%= link_to t('.payment', :default => t("helpers.links.payment")), new_payment_path(:customer_id => order.customer_id, :order_id => order.id), :class => 'btn btn-info btn-xs btn-danger pull-right' %>
        <%= link_to t('.addOrder', :default => t("helpers.links.addOrder")), new_order_detail_path(:order_id => order.id), :class => 'btn btn-primary btn-xs pull-right' %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_order_path(order), :class => 'btn btn-info btn-xs pull-right' %>
        <%= link_to t('.show', :default => t("helpers.links.show")), order_path(order), :class => 'btn btn-info btn-xs pull-right' %>
      </div>
    </div>
<% end %>

app/views/orders/edit.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/orders/index.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>

<%= form_for :search, url: search_orders_path, :html => { :class => "form-horizontal order" } do |f| %>
  <div class="col-xs-12 " style="padding:5px;">
  <div class="form-group">
    <div class="col-xs-12">
      <div class="input-group">
        <span class="input-group-addon"><%= (t '.customer') %></span>
        <%= f.collection_select :customer_id, list_customers_for_combobox, :id, :name, {:selected =>@params && @params["customer_id"], :include_blank => (t '.prompt')}, {:class => 'form-control'}%>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-remove-circle"></span>
        </span>
      </div>
    </div>
    <%=f.error_span(:customer_id) %>
  </div>

  <div class="form-group">
    <div class="col-xs-12">
      <div class="input-group">
        <span class="input-group-addon"><%= (t '.status') %></span>
        <%= f.select :status, Order.statuses.keys.to_a.map { |s| [t("activerecord.enums.order.status.#{s}"), s]} , {:selected =>@params && @params["status"], :include_blank => (t '.prompt')}, {:class => 'form-control'} %>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-remove-circle"></span>
        </span>
      </div>
    </div>
    <%=f.error_span(:status) %>
  </div>

  </div>
  <div class="col-xs-12" style="padding:5px;">
  <%= link_to t('.new', :default => t("helpers.links.new")),new_order_path, :class => 'btn btn-primary' %>
  <%= f.submit t('.search'), :class => 'btn btn-primary' %>
  </div>
<% end %>
  <hr/>

<%= render :partial => 'list', locals: {orders: @orders}%>
<%= javascript_include_tag "common/remomve_button_for_select" %>

app/views/orders/new.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/orders/show.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.titleize %></h2>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:customer) %>:</strong></dt>
  <dd><%= @order.customer.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:note) %>:</strong></dt>
  <dd><%= @order.note %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @order.status %></dd>
</dl>

<hr/>

<%= link_to t('.back', :default => t("helpers.links.back")),
              orders_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_order_path(@order), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              order_path(@order),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<%= link_to t('.addOrder', :default => t("helpers.links.addOrder")),
            new_order_detail_path(:order_id => @order.id), :class => 'btn btn-default' %>

<hr/>
<%= render :partial => 'order_details/list', locals: {order_details: list_order_details(@order)}%>