config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  get 'rakuten/query'
  get 'goods/query'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#authorize'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  constraints(id: /[0-9]+/) do
    resources :goods do
      collection do
        post :search
      end
    end
  end

  resources :customers, constraints: { id: /[0-9]+/ }

  constraints(id: /[0-9]+/) do
    resources :orders do
      collection do
        post :search
      end
    end
  end

  constraints(id: /[0-9]+/) do
    resources :order_details do
      collection do
        post  :search
      end
    end
  end

  constraints(id: /[0-9]+/) do
    resources :payments do
      collection do
        post  :search
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#hello'
end

app/models/payment.rb
class Payment < ApplicationRecord

  validates :order_id, numericality: {only_integer: true}, presence: true
  validates :customer_id, numericality: {only_integer: true}, presence: true
  validate  :validate_order_id
  validate  :validate_customer_id

  belongs_to :order
  belongs_to :customer

  def self.search(params = {})
    Payment.joins(:customer, :order).select("payments.*, customers.name as customer_name, orders.note as order_node")
      .where(create_conditions(params)).order({id: :desc})
  end

  # raise system exception
  def validate_order_id
    Order.find(order_id) rescue raise SystemError
  end
  # raise system exception
  def validate_customer_id
    Customer.find(customer_id) rescue raise SystemError
    errors.add(:customer_id, "is wrong.") unless Order.find(order_id).customer_id == customer_id
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :payment_search_params, only: [:search]
  before_action :check_order_info, only: [:update, :create]
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.search(attach_owner_user_id)
  end

  # POST /orders/search
  def search
    @payments = Payment.search(@params)
    render "index"
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new(new_params)
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(attach_owner_user_id(payment_params))
    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = check_owner_user_id(Payment.find(params[:id]))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:order_id, :customer_id, :amounts, :payment_method, :note)
    end

    def payment_search_params
      @params = params.require(:search).permit(:order_id, :customer_id)
    end

    def new_params
      check_customer_id
      check_order_id
      params.permit(:order_id, :customer_id)
    end

    def check_order_info
      params = payment_params
      raise SystemError if Order.where(attach_owner_user_id({:id => params[:order_id],
                                                              :customer_id => params[:customer_id]})).empty?
    end
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/views/payments/_form.html.erb
<%= form_for @payment, :html => { :class => "form-horizontal payment" } do |f| %>

  <% if @payment.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @payment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :order_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= select :payment, :order_id,
            options_for_select(list_orders_for_combobox.map{|t| [t.note, t.id,
                                                                {:disabled => @payment.order_id && t.id != @payment.order_id}
                                                              ]}),
                                {:selected => @payment.order_id},
                                {:class => 'form-control'}
                              %>

    </div>
    <%=f.error_span(:order_id) %>
  </div>
  <div class="form-group">
    <%= f.label :customer_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= select :payment, :customer_id,
            options_for_select(list_customers_for_combobox.map{|t| [t.name, t.id,
                                                                    {:disabled => @payment.customer_id && t.id != @payment.customer_id}
                                                                  ]}),
                                {:selected => @payment.customer_id},
                                {:class => 'form-control'}
                              %>


    </div>
    <%=f.error_span(:customer_id) %>
  </div>
  <div class="form-group">
    <%= f.label :amounts, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :amounts, :class => 'form-control', :pattern => '[0-9]*'%>
    </div>
    <%=f.error_span(:amounts) %>
  </div>
  <div class="form-group">
    <%= f.label :payment_method, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :payment_method, :class => 'form-control' %>
    </div>
    <%=f.error_span(:payment_method) %>
  </div>
  <div class="form-group">
    <%= f.label :note, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :note, :class => 'form-control' %>
    </div>
    <%=f.error_span(:note) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                order_path(@payment.order_id), :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/payments/edit.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/payments/index.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>


<%= form_for :search, url: search_payments_path, :html => { :class => "form-horizontal order" } do |f| %>
  <div class="col-xs-12 " style="padding:5px;">
  <div class="form-group">
    <div class='col-xs-12'>
      <div class="input-group">
        <span class="input-group-addon"><%= (t '.order') %></span>
        <%= f.collection_select :order_id, list_orders_for_combobox, :id, :note, {:selected =>@params && @params["order_id"], :include_blank => (t '.prompt')}, {:class => 'form-control'}%>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-remove-circle"></span>
        </span>
      </div>
    </div>
    <%=f.error_span(:order_id) %>
  </div>

  <div class="form-group">
    <div class='col-xs-12'>
      <div class="input-group">
        <span class="input-group-addon"><%= (t '.customer') %></span>
        <%= f.collection_select :customer_id, list_customers_for_combobox, :id, :name, {:selected =>@params && @params["customer_id"], :include_blank => (t '.prompt')}, {:class => 'form-control'}%>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-remove-circle"></span>
        </span>
      </div>
    </div>
    <%=f.error_span(:customer_id) %>
  </div>

  </div>
  <div class='col-xs-12' style="padding:5px;">
  <%= f.submit t('.search'), :class => 'btn btn-primary' %>
  </div>
<% end %>
<hr/>


<% @payments.each do |payment| %>
<div class='col-xs-12 list-group-item' style='padding:5px;'>
  <div class='col-xs-12' style='margin-bottom:5px;'>
    <%= link_to payment_path(payment) do%>
      <span class='label label-default'><%= payment.id %>-<%= payment.created_at.strftime("%Y/%m/%d") %></span>
    <% end %>
  </div>
  <div class='col-xs-2'>
    <span class='label label-default'><%= t '.order' %></span>
  </div>
  <div class='col-xs-10' style='margin-bottom:5px;'>
      <%= link_to payment.attributes["order_node"], order_path(payment.order_id) %>
  </div>
  <div class='col-xs-2'>
    <span class='label label-default'><%= t '.customer' %></span>
  </div>
  <div class='col-xs-10' style='margin-bottom:5px;'>
    <%= link_to payment.attributes["customer_name"], customer_path(payment.customer_id) %>
  </div>

  <div class='col-xs-2'>
    <span class='label label-default'><%= t '.payment_method' %></span>
  </div>
  <div class="col-xs-4">
    <span class='pull-right'><%= payment.payment_method %></span>
  </div>
  <div class='col-xs-6'>
    <span class="label label-danger pull-left"><%= number_to_currency(payment.amounts, :unit=>"CNY") %></span>
  </div>

  <div class='col-xs-12'>
    <%= payment.note %>
  </div>
  <div class='col-xs-12'>
    <%= link_to t('.edit', :default => t('helpers.links.edit')),
    edit_payment_path(payment), :class => 'btn btn-default btn-xs  pull-right' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
    payment_path(payment),
    :method => :delete,
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
    :class => 'btn btn-xs btn-danger  pull-right' %>
  </div>
</div>
<% end %>


<%= javascript_include_tag "common/remomve_button_for_select" %>
<%= javascript_include_tag "payments/payments" %>

app/views/payments/new.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/payments/show.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.titleize %></h2>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:order_id) %>:</strong></dt>
  <dd><%= @payment.order_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_id) %>:</strong></dt>
  <dd><%= @payment.customer_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amounts) %>:</strong></dt>
  <dd><%= @payment.amounts %></dd>
  <dt><strong><%= model_class.human_attribute_name(:payment_method) %>:</strong></dt>
  <dd><%= @payment.payment_method %></dd>
  <dt><strong><%= model_class.human_attribute_name(:note) %>:</strong></dt>
  <dd><%= @payment.note %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              payments_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_payment_path(@payment), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              payment_path(@payment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>