config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  get 'rakuten/query'
  get 'goods/query'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#authorize'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  constraints(id: /[0-9]+/) do
    resources :goods do
      collection do
        post :search
      end
    end
  end

  resources :customers, constraints: { id: /[0-9]+/ }

  constraints(id: /[0-9]+/) do
    resources :orders do
      collection do
        post :search
      end
    end
  end

  constraints(id: /[0-9]+/) do
    resources :order_details do
      collection do
        post  :search
      end
    end
  end

  constraints(id: /[0-9]+/) do
    resources :payments do
      collection do
        post  :search
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#hello'
end

app/models/good.rb
class Good < ApplicationRecord
  validates :jan_cd, format: {with: /\A\z|\A[0-9]{13}\z/, multiline: false}
  validates :name_jp, length: {maximum: 255}, presence: true
  validates :name_cn, length: {maximum: 255}, presence: false
  validates :price_jpy, numericality: {only_integer: true, greater_than: 0}, presence: true
  validates :selling_price_cny, numericality: {greater_than: 0}, presence: true
  validates :profit_rate, numericality: {only_integer: true, greater_than: 0}, presence: true

  scope :goods_name_like, ->(params) {
    keyword = "%#{sanitize_sql_like(params[:keyword])}%"
    where("owner_user_id = ? AND (name_jp LIKE ? or name_cn LIKE ?)", params[:owner_user_id], keyword, keyword)
  }
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: [:show, :edit, :update, :destroy]
  before_action :search_params, only: [:search]
  # GET /goods
  # GET /goods.json
  def index
    @goods = Good.where(attach_owner_user_id).order({id: :desc})
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
  end

  # GET /goods/new
  def new
    @good = Good.new
  end

  # GET /goods/1/edit
  def edit
  end

  # POST /goods/search
  def search
    if(@params["keyword"].empty?)
      @goods = Good.where(attach_owner_user_id)
    else
      @goods = Good.goods_name_like(@params)
    end
    render 'index'
  end

  # GET /goods/query
  def query
    keyword_hash = {:keyword => params[:keyword]}
    render :json => Good.goods_name_like(attach_owner_user_id(keyword_hash))
  end
  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(attach_owner_user_id(good_params))

    respond_to do |format|
      if @good.save
        format.html { redirect_to @good, notice: 'Good was successfully created.' }
        format.json { render :show, status: :created, location: @good }
      else
        format.html { render :new }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to @good, notice: 'Good was successfully updated.' }
        format.json { render :show, status: :ok, location: @good }
      else
        format.html { render :edit }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to goods_url, notice: 'Good was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = check_owner_user_id(Good.find(params[:id]))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:good).permit(:jan_cd, :name_jp, :name_cn, :price_jpy, :profit_rate, :selling_price_cny, :image_path)
    end

    def search_params
      @params = params.require(:search).permit(:keyword)
      @params = attach_owner_user_id(@params)
    end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_form.html.erb
<% current_rate = Rate.current_rate.first.rate %>

<%= form_for @good, :html => { :class => "form-horizontal good" } do |f| %>

  <% if @good.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@good.errors.count, "error") %> prohibited this good from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @good.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-xs-12">
      <%= f.label :jan_cd, :class => 'control-label' %>
      <div class="input-group">
        <%= f.text_field :jan_cd, :class => 'form-control', :placeholder=>"45XXXXXXXX123", :pattern => '[0-9]{13}'%>
        <span class="input-group-btn">
          <button id="jan_cd_rakuten_query" class="btn btn-default" type="button">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div><!-- /input-group -->
    </div><!-- /.col-xs-12 -->
  </div><!-- /.row -->

  <div class="form-group">
    <div class="col-xs-12">
      <%= f.label :name_jp, :class => 'control-label' %>
      <div class="input-group">
        <%= f.text_field :name_jp, :class => 'form-control' %>
        <span class="input-group-btn">
          <button id="name_jp_rakuten_query" class="btn btn-default" type="button">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div><!-- /input-group -->
    </div><!-- /.col-xs-12 -->
  </div><!-- /.row -->

  <div class="form-group">
    <div class="col-xs-12">
      <%= f.label :name_cn, :class => 'control-label' %>
      <%= f.text_field :name_cn, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name_cn) %>
  </div>
  <div class="form-group">
    <div class="col-xs-12">
      <%= f.label :price_jpy, :class => 'control-label' %>
      <%= f.text_field :price_jpy, :class => 'form-control', :pattern =>'[0-9]*' %>
    </div>
    <%=f.error_span(:price_jpy) %>
  </div>
  <div class="form-group">
    <div class="col-xs-12">
      <%= f.label :profit_rate, :class => 'control-label' %>
      <%= f.text_field :profit_rate, :class => 'form-control', :value=>"10", :pattern => '[0-9]*'%>
    </div>
    <%=f.error_span(:profit_rate) %>
  </div>
  <div class="form-group">
    <div class="col-xs-12">
      <%= f.label :selling_price_cny, :class => 'control-label' %>
      <%= f.label "current_rate_label", "#{current_rate}" %>
      <%= f.text_field :selling_price_cny, :class => 'form-control', :pattern => '[0-9]*'%>
    </div>
    <%=f.error_span(:selling_price_cny) %>
  </div>
  <div class="form-group">
    <div class="col-xs-12">
      <%= f.label :image_path, :class => 'control-label' %>
      <%= f.text_field :image_path, :class => 'form-control' %>
    </div>
    <%=f.error_span(:image_path) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-12">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                goods_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
        <table class="table">
            <tr>
              <th scope="row">1</th>
              <td>Table cell</td>
            </tr>
        </table>
    </div>
  </div>
</div>
<%= javascript_include_tag "goods/goods" %>
<%= javascript_tag do%>
var current_rate = <%= current_rate %>
<% end %>

app/views/goods/edit.html.erb
<%- model_class = Good -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/goods/index.html.erb
<%- model_class = Good -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>
<%= form_for :search, url: search_goods_path, :html => { :class => "form-horizontal good" }  do |f| %>
  <div class="col-xs-12 " style="padding:5px;">
    <div class="form-group">
      <div class="col-lg-12">
        <div class="input-group">
          <span class="input-group-addon"><%= (t '.good') %></span>
          <%= f.text_field :keyword, :class => 'form-control', :value => @params && @params["keyword"], :placeholder=> (t '.good-placeholder')%>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-remove-circle"></span>
          </span>
        </div>
      </div>
      <%=f.error_span(:order_id) %>
    </div>
  </div>
  <div class="col-xs-12" style="padding:5px;">
  <%= link_to t('.new', :default => t("helpers.links.new")),new_good_path, :class => 'btn btn-primary' %>
  <%= f.submit t('.search'), :class => 'btn btn-primary' %>
  </div>
<% end %>
<hr/>
  <% @goods.each do |good| %>
    <div class="col-xs-12 list-group-item" style="padding:5px;">
      <div class="col-xs-12" style="margin-bottom:5px;">
        <span class="label label-danger"><%= number_to_currency(good.price_jpy)%></span>
        <span class="label label-primary"><%= good.profit_rate %>%</span>
        <span class="label label-default"><%= number_to_currency(good.selling_price_cny, :unit=> "CNY") %></span>
      </div>
      <div class="col-xs-3" style="padding-left:0px;"> <%= link_to image_tag(good.image_path), good_path(good)%> </div>
      <div class="col-xs-9" style="padding-right:0px;">
        <p class="list-group-item-heading bg-success"><%= good.name_jp %></p>
        <p class="list-group-item-heading bg-warning"><u><%= good.name_cn %></u></p>
      </div>

      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_good_path(good), :class => 'btn btn-info btn-xs pull-right' %>
    </div>
  <% end %>
</div>
<%= javascript_include_tag "goods/goods" %>

app/views/goods/new.html.erb
<%- model_class = Good -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/goods/show.html.erb
<%- model_class = Good -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.titleize %></h2>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:jan_cd) %>:</strong></dt>
  <dd><%= @good.jan_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name_jp) %>:</strong></dt>
  <dd><%= @good.name_jp %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name_cn) %>:</strong></dt>
  <dd><%= @good.name_cn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price_jpy) %>:</strong></dt>
  <dd><%= @good.price_jpy %></dd>
  <dt><strong><%= model_class.human_attribute_name(:profit_rate) %>:</strong></dt>
  <dd><%= @good.profit_rate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:selling_price_cny) %>:</strong></dt>
  <dd><%= @good.selling_price_cny %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_path) %>:</strong></dt>
  <dd><%= image_tag(@good.image_path) %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              goods_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_good_path(@good), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              good_path(@good),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>